### ISSUE TITLE
jira-server-3.png Image is Misleading

### ISSUE THREAD

**Issue by antoineh1** [Hacker0x01/docs.hackerone.com#176]
I find the appearance of this image very misleading. On multiple occasions, I think it is a link to the specific documentation for Jira Cloud or Jira Server, but it just loads the image in a new tab.
I admit it is my fault for not reading the page more thoroughly before clicking but is there anything that can be done to prevent the image from opening in a new tab when clicked?

**Comment by stacyspiva** [comment]
@antoineh1 I feel your pain. Thank you for your feedback. I agree that this functionality is not ideal. This is something that I brought up to engineers before, but they just don't have the bandwidth to go about fixing it. Since it's not causing major issues, but is just more of an annoyance, it's something that can wait in getting fixed once engineers have more time. I'll be sure to bring it up in their backlog so that they can consider this project when they have time.

**Comment by reedloden** [comment]
This is a one-line change to fix (to not linkify images), but just want to make sure it's wanted. If you want to try it locally to confirm it's what you would expect, here's the diff:

```diff
diff --git a/gatsby-config.js b/gatsby-config.js
index 6986c7b0a7..2b81835812 100644
--- a/gatsby-config.js
+++ b/gatsby-config.js
@@ -63,7 +63,8 @@ module.exports = {
           {
             resolve: 'gatsby-remark-images',
             options: {
-              maxWidth: 500
+              maxWidth: 500,
+              linkImagesToOriginal: false
             },
           },
         ],
```

**Comment by stacyspiva** [comment]
@antoineh1 just ran the change that removes the ability to click images. Hopefully this helps

Thank you @reedloden for providing the diff!

**Comment by antoineh1** [comment]
Thank you for the quick update!

**Comment by reedloden** [comment]
Fixed by https://github.com/Hacker0x01/docs.hackerone.com/commit/41e93d0395dd373b96241fe7fb5dd4e9d5fc55da
